color: /home/haru/Documents/active_marker_gui/pattern_calibrator/src/pattern_calibrator/color_config.yaml
ref: /home/haru/Documents/active_marker_gui/pattern_calibrator/src/pattern_calibrator/color_ref.yaml
result: /home/haru/Documents/active_marker_gui/pattern_calibrator/src/pattern_calibrator/config_result.yaml
log: /home/haru/Documents/active_marker_gui/pattern_calibrator/src/pattern_calibrator/test.csv
camera: /home/haru/Documents/active_marker_gui/pattern_calibrator/src/pattern_calibrator/camera.yaml