blue:
  red:
    b: 0
    i: 0
    d: 0
    h: 0
  green:
    b: 0
    i: 0
    d: 0
    h: 0
  blue:
    b: 86.9381
    i: -0.0743
    d: 0.1276
    h: -0.1168
yellow:
  red:
    b: 99.9770
    i: -0.0476
    d: 0.1346
    h: -0.1169
  green:
    b: 100.1249
    i: -0.0476
    d: 0.1349
    h: -0.1172
  blue:
    b: 0
    i: 0
    d: 0
    h: 0
pink:
  red:
    b: 180.9802
    i: -0.0656
    d: 0.1443
    h: -0.1222
  green:
    b: 0
    i: 0
    d: 0
    h: 0
  blue:
    b: -16.8402
    i: -0.0401
    d: 0.1501
    h: -0.1188
green:
  red:
    b: 0
    i: 0
    d: 0
    h: 0
  green:
    b: 201.1071
    i: -0.0893
    d: 0.1581
    h: -0.1371
  blue:
    b: 0
    i: 0
    d: 0
    h: 0